### ISSUE TITLE
Cache locally on iOS devices

### ISSUE THREAD

**Issue by jonicious** [snapsnapturtle/weatherapp#25]
You can find more information [here](https://developer.apple.com/library/safari/documentation/iPhone/Conceptual/SafariJSDatabaseGuide/OfflineApplicationCache/OfflineApplicationCache.html)

**Comment by snapsnapturtle** [comment]
[first caching of images](https://github.com/snapsnapturtle/weatherapp/commit/6a572197a5efee3c4a642f3b633c967b0ee24168?diff=unified)

**Comment by snapsnapturtle** [comment]
wont work on github pages, [see here](http://stackoverflow.com/questions/22182863/appcache-fatal-error)

**Comment by snapsnapturtle** [comment]
wont work on github pages, [see here](http://stackoverflow.com/questions/22182863/appcache-fatal-error)

**Comment by jonicious** [comment]
Ugh, we should consider ditching Github Pages and use our own server.
